[package]
name = "simple-buffer"
version = "0.1.0"
edition = "2021"

[features]
default = ["ring"]
ring = ["dep:ringbuf"]

[dependencies]
ringbuf = { version = "0.3", optional = true, features = ["alloc"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
